### ISSUE TITLE
Can't find the right object？

### ISSUE THREAD

**Issue by alphabetabc** [pmndrs/drei#1194]
### What is your question:

in this example  **[horizontal-tiles](https://codesandbox.io/s/l4klb)**  , i can't find the right object , because  the object position has shifed.

i add this style in my project
```css
#root {
    max-width: 1280px;
    margin: 0 auto;
    width: 100%;
    height: 100%;
}

```

![image](https://user-images.githubusercontent.com/29876424/209289395-b93eb316-59eb-478c-ba41-b584aa722366.png)
