### ISSUE TITLE
<Html /> becomes misaligned when placed in a grid

### ISSUE THREAD

**Issue by markryanbotha** [pmndrs/drei#428]
- `three` version: 0.129.0
- `@react-three/fiber` version: 6.2.2
- `@react-three/drei` version: 5.3.0

### Problem description:

When I place a model inside a CSS grid, and I use the grid system to resize and place the item, the items within the Html tags are no longer aligned with the surface of the model.

When the page is resized, the items in the HTML tag also jump around.

### Relevant code:

Here is the codesandbox with the code: https://codesandbox.io/s/mixing-html-and-webgl-w-occlusion-forked-ct4fl?file

This only seems to occur when the initial grid or row is not 1.

For example, this code works

```css
.canvas {
  grid-row: 1/11;
  grid-column: 1/11;
}
```

However, this code does not

```css
.canvas {
  grid-row: 4/11;
  grid-column: 4/11;
}
```

Please let me know if you are not meant to use containers with CSS to place react-three-fiber models
